/* We first check whether the required elements exist on the webpage. If they
 * do not, it means that either the user is looking at something other than
 * a project page, or that github changed their layout and we need to adapt
 * this code. Either way, this ensures that no errors are generated by this
 * extension due to missing DOM elements. */
var selectors =
    [ 'h1.entry-title > strong > a'
    , '.js-repo-list h3.repolist-name a:first-child'
    , '.org-repo-name a'
    ];

selectors.forEach(function(sel) {
    console.log("Selecting");
    var els = window.document.querySelectorAll(sel);
    for (var i = 0, l = els.length; i < l; i++) {
        insertStatusIcon(els[i]);
    }
});

function insertStatusIcon(el) {
    console.log("Inserting");
    var project = el.pathname;

    /* Create the link element. */
    var link = window.document.createElement('a');
    link.text = "Checkout locally!"
    link.href = 'foo://' + window.location.href;

    el.parentNode.insertBefore(link, el.nextSibling);
}
